__version__ = "1.0.3"
__authors__ = "Daren Race"
__license__ = "Apache License, Version 2.0, January 2004"
__contact__ = "daren.race@gmail.com"
__license__ = "Apache License"
__description__ = "Generate names for things with phonetic alliteration - use with GUIDs for easy identification."
